### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by suresh-s** [udacity/CarND-Advanced-Lane-Lines#23]
How to run this project?  
Could you tell me the steps to run?

**Comment by mvirgo** [comment]
Hi there! This project is part of the [Udacity Self-Driving Car Engineer Nanodegree program](https://www.udacity.com/course/self-driving-car-engineer-nanodegree--nd013). The notes included as part of the README are the only instructions we provide outside of the classroom.

**Comment by SJTUPanda** [comment]
So, no core part of code. Good video and note, what a pity

**Comment by UAnjali** [comment]
Hi, 
We are closing out the issue. You can find this project in the [Udacity Self-Driving Car Engineer Nanodegree program](https://www.udacity.com/course/self-driving-car-engineer-nanodegree--nd013).
Thank you
